### ISSUE TITLE
extension field does not clear itself on submit

### ISSUE THREAD

**Issue by Cyrelc** [JackSchaible/FastForward-Express#103]
When submitting a new contact (hitting the "save button") on the multi-contacts page, if you include an extension field, it does not get cleared when creating the new contact, instead it is copied and stays populated in the "new" view.

**Comment by JackSchaible** [comment]
Fixed in [PR 106](https://github.com/JackSchaible/FastForward-Express/pull/106/commits/30022e54354f35471e6edd0d185a39cd3d208346)
