### ISSUE TITLE
Jack's Homework 09/23/2017

### ISSUE THREAD

**Issue by Cyrelc** [JackSchaible/FastForward-Express#118]
@JackSchaible please make the following DB changes at your convenience, AFTER reviewing my current PR:

1) On bills, change the field named "type" to "delivery_type"
2) On Invoices, add the following fields (all are type float): "balance_owing", "bill_cost", "tax", "total_cost", "fuel_surcharge" and "discount" -> nullable();
3) From "bills" remove "weight", "height", "length", and "width". Create a new table called "packages" with these attributes. Packages have a required "bill_id" (one bill to many packages) field, so they can be linked back. I realized the current system will not work if there are two or more different packages with different weights and dimensions.
4) Modify the query which gathers accounts with uninvoiced bills for invoicing, to ignore accounts which are currently set as "disabled"
5) On accounts, unless you have a compelling reason to keep it, remove "is_master" field. Change "gets_discount" to "has_discount", add new item "send_invoices" which is a boolean, and defaults to  #true.
6) What is the "severities" table? Did we create this or is it Laravel specific? --> merge into selections table
7) On expiries change "grace" to "grace_days"
8) On chargebacks table, what is "gl_code"?
9) What are the "reference types" and "references" tables? --> delete
10) Talk to Brandon about "change tracking"

**Comment by JackSchaible** [comment]
1. You did

**Comment by JackSchaible** [comment]
2. Done in https://github.com/JackSchaible/FastForward-Express/commit/da4577dd812be6d834bbd457dd9146690d996d9e

**Comment by JackSchaible** [comment]
3. Done in https://github.com/JackSchaible/FastForward-Express/commit/549f055c11c7d725f7544a6271294b33ddeb4566

**Comment by JackSchaible** [comment]
4. Done in https://github.com/JackSchaible/FastForward-Express/commit/32cf196ba30fe5b0223ac1a30b789a33013a2f32

**Comment by JackSchaible** [comment]
5. Done in https://github.com/JackSchaible/FastForward-Express/commit/32cf196ba30fe5b0223ac1a30b789a33013a2f32

**Comment by JackSchaible** [comment]
6. Done in https://github.com/JackSchaible/FastForward-Express/commit/19ef84ffbbaf660b7e666a0b11f0343b596ad1fc

**Comment by JackSchaible** [comment]
7. Done in https://github.com/JackSchaible/FastForward-Express/commit/19ef84ffbbaf660b7e666a0b11f0343b596ad1fc

**Comment by JackSchaible** [comment]
8. No action
9. Done in https://github.com/JackSchaible/FastForward-Express/commit/6a78cbb962314ae8bff49d0d59486cd5f8ff5c2e
10. Seperate ticket created at https://github.com/JackSchaible/FastForward-Express/issues/121
